GET http://localhost:5000/api/posts

###
DELETE http://localhost:5000/api/posts/63ae53821145fe4ab3b19010

###
POST http://localhost:5000/api/posts
Content-Type: application/json

{
    "user" : "Mouri",
    "post": "ASA University Bangladesh",
    "photoUrl": "NA",
    "like": 37
}